#!/bin/bash
set -euo pipefail

MYSQL_DATABASE=${MYSQL_DATABASE:-dbmanager}
MYSQL_USER=${MYSQL_USER:-db_admin}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
MYSQL_READ_USER=${MYSQL_READ_USER:-db_read}
MYSQL_READ_PASSWORD=${MYSQL_READ_PASSWORD:-}

if [ -z "$MYSQL_PASSWORD" ] || [ -z "$MYSQL_READ_PASSWORD" ]; then
  echo "MYSQL_PASSWORD and MYSQL_READ_PASSWORD must be set before MySQL initialization runs." >&2
  exit 1
fi

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_USER}'@'%' REQUIRE SSL;
CREATE USER IF NOT EXISTS '${MYSQL_READ_USER}'@'%' IDENTIFIED BY '${MYSQL_READ_PASSWORD}';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_READ_USER}'@'%' REQUIRE SSL;
FLUSH PRIVILEGES;
SQL
