CREATE DATABASE IF NOT EXISTS dbmanager;
CREATE USER IF NOT EXISTS 'db_admin'@'%' IDENTIFIED BY 'Adm1n@DB2026!';
GRANT ALL PRIVILEGES ON dbmanager.* TO 'db_admin'@'%' REQUIRE SSL;
CREATE USER IF NOT EXISTS 'db_read'@'%' IDENTIFIED BY 'User@2026!';
GRANT SELECT ON dbmanager.* TO 'db_read'@'%' REQUIRE SSL;
FLUSH PRIVILEGES;
